[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[watch]
ignorePatterns = ["node_modules/**", "vendor/**", "storage/**", "*.md"]
