[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[watch]
ignorePatterns = ["node_modules/**", "vendor/**", "storage/**", "*.md"]
